### ISSUE TITLE
Support IntelliJ IDEA 2023.1

### ISSUE THREAD

**Issue by QwerTech** [amazon-ion/ion-intellij-plugin#48]
I have a plugin of version 2.2.0+5-IC-2022.2 installed, but it seems that it doesn't support 2023.1 Idea versions.
It says Incomparable: requires IDE build 223.* or earlier.

My IntelliJ IDEA version is:
IntelliJ IDEA 2023.1 (Ultimate Edition)
Build #IU-231.8109.175, built on March 28, 2023

<img width="483" alt="image" src="https://user-images.githubusercontent.com/5159817/232104986-9d25d995-cb8f-4344-a12d-43280ca85de2.png">

**Comment by londonbrown** [comment]
In the meantime, you can use the Beta version of Amazon Ion IntelliJ plugin that's compatible with 2023.1: https://plugins.jetbrains.com/plugin/8409-amazon-ion/versions/beta/282589

**Comment by QwerTech** [comment]
Actually, I stated using it, but the formatting isn't working there.

**Comment by QwerTech** [comment]
Hello @londonbrown, I'm new with the Idea plugin development, but I've created #49 to address the issue with formatting for Idea 2023. Could you please take a look?
