### ISSUE TITLE
Support IntelliJ IDEA 2024.1

### ISSUE THREAD

**Issue by Yuyangbo** [amazon-ion/ion-intellij-plugin#62]
I recently upgraded Idea to Build #IU-241.14494.240, where Ion plugin is not supported yet. 
<img width="376" alt="Idea plugin ion" src="https://github.com/amazon-ion/ion-intellij-plugin/assets/55121119/77f986c9-4e12-407b-bb9b-5c20c3bee0b3">

Looking forward for supporting this new version.

**Comment by popematt** [comment]
Thanks for bringing this to our attention. We will look into it.

**Comment by nirosys** [comment]
2.6.0 has been released to support 2024.1. Thank you again for bringing this to our attention!
